name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * 0-6"  # Run daily at midnight (00:00) on any day of the week

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate random number
        id: random-number
        run: echo "::set-output name=number::$(shuf -i 1-7 -n 1)"

      - name: Set up Git
        run: |
          git config --global user.name 'Vishal Barot'
          git config --global user.email 'barotvishal12@outlook.com'

      - name: Make changes
        run: |
          echo "random commit" > random.txt
          git add .
          git commit -m "Auto commit changes on random day of the week: ${{ steps.random-number.outputs.number }}"
          git push



